package com.violentgentlemenstudios.riot.res.cutscenes;

import com.violentgentlemenstudios.riot.*;

public class SceneIntro extends Cutscene {
    
    public void setupActors() {
        actors.put("player", EntityManager.getPlayer());
        
        commands = newCommands;
    }
    
    protected SceneCommand[] newCommands = {
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5),
        new SceneCommand("move", "player", Direction.LEFT, 5)
    };
}
